site_name: JPL Open Source Rover
site_url: https://open-source-rover.readthedocs.io
site_description: |
  A build-it-yourself, 6-wheel rover based on the rovers on Mars!
copyright: |
  Copyright &copy; 2018 California Institute of Technology. Government Sponsorship Acknowledged.

docs_dir: .
site_dir: _site
use_directory_urls: false
repo_url: https://github.com/nasa-jpl/open-source-rover
edit_uri: edit/master

nav:
  - Home: README.md
  - Electrical:
      - Overview: electrical/README.md
      - Wiring: electrical/wiring/README.md
      - PCB assembly: electrical/pcb/README.md
  - Mechanical:
      - Overview: mechanical/README.md
      - Wheel assembly: mechanical/wheel_assembly/README.md
      - Body: mechanical/body/README.md
      - Rocker bogie: mechanical/rocker_bogie/README.md
  - Parts:
      - Parts list: parts_list/README.md
      - Optional parts: mechanical/optional_cad_parts/README.md
  - Software:
      - Software on GitHub: https://github.com/nasa-jpl/osr-rover-code
  - OSR@JPL: https://jplopensourcerover.com/

plugins:
  - same-dir
  - search:
      prebuild_index: true

markdown_extensions:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_alt

theme:
  name: readthedocs
